### ISSUE TITLE
Missing gulp build?

### ISSUE THREAD

**Issue by jforaker** [thekelvinliu/generator-espress#1]
```
yo-express gulp build
[01:23:01] Using gulpfile ~/dev/node/yo-express/gulpfile.js
[01:23:01] Task 'build' is not in your gulpfile
[01:23:01] Please check the documentation for proper gulpfile formatting
```

**Comment by thekelvinliu** [comment]
first, thanks for checking out the generator! i'm sorry to see you're running into some trouble, but the information you gave doesn't really give me a good sense of what's going on here. could you give me some more background as to how you got there?

one thing that jumps out at me is the name of the gulpfile being used above. it seems to be `gulpfile.js` and not `gulpfile.babel.js`. my generator only creates the latter, as it allows for es6 syntax to be used in the gulpfile itself. did you happen to rename the file? or, did a different gulpfile somehow find its way into the directory?

**Comment by jforaker** [comment]
Ohhh boy.  My mistake!  I used `yo express`  with an "x"!  Must have been 😴
